### ISSUE TITLE
Multiple input tex files

### ISSUE THREAD

**Issue by Weiming-Hu** [jwcarr/bibfish#1]
Hi,

Thank you for the awesome tool. I'm wondering how/whether it supports multiple input tex files? For example, I have a `main.tex` where it pulls content from other tex files, e.g. `\input{chapter1.tex}`. Will content from `chapter1.tex` be automatically included?

**Comment by jwcarr** [comment]
I'm more of a dump-everything-in-one-file kinda guy, so I never thought about this. Currently this is not supported because bibfish does not do any kind of parsing of the latex/bibtex. But it would be relatively easy to add this feature, I think.

Basically, the `extract_citekeys` function would just search the file for `\input{}`s and recursively call itself to extract citekeys from the other files. I'm not super familiar with typical usage patterns of `\input{}` (and also `\include{}`), so I'm guessing there could be a few gotchas to think about.

If you have time/inclination, feel free to have a go at this yourself. If not, I might get round to it at some point. For now, I'll tag as a new feature request.

**Comment by Weiming-Hu** [comment]
Sounds good. I guess I can work on a PR if I have some time. Basically, I can add a list of patterns to match, e.g., `\input{}` and `\include{}`, and then recursive expand the command to its actual content before parsing the keys. What do you think?

**Comment by jwcarr** [comment]
Yep, sounds perfect!

**Comment by jwcarr** [comment]
This has been implemented in PR #3 and is available in version 0.1.
