### ISSUE TITLE
Make .bib file parsing more robust

### ISSUE THREAD

**Issue by rbeyer** [jwcarr/bibfish#5]
The *bibfish* regex parsing did not parse my weird .bib files (but there is a warning for that, so not a surprise). I tried to see if I could expand the regex parsing for my weird .bib files, but regex parsing is rarely robust, and I found [BibtexParser](https://bibtexparser.readthedocs.io/) which seems pretty functional.

Would you be interested in a PR that adds BibtexParser as a requirement for *bibfish* (which would allow for more robust .bib file parsing) and uses it to parse .bib files for *bibfish*?

**Comment by jwcarr** [comment]
This is an interesting idea and I'm open to exploring it some more, but I suspect it won't fit so well with my minimalist philosophy. In particular:

1. I rather like the fact that Bibfish doesn't do any serious parsing of the bibtex/latex because this gives the user maximum flexibility to construct entries however they like. (For example, I just tried running BibtexParser on my database and it didn't like my `@presentation` and `@magazine` entries, and it reorders the fields alphabetically).
2. This would add two dependencies, BibtexParser and PyParsing, which I will have to stay up-to-date with going forward.
3. BibtexParser seems to be very fast and solid, but it does take a little bit of time to do a full parse of the bibtex – possibly this won't scale well with much larger databases than my own.
4. BibtexParser has lots of customization options, so we'd have to either (a) enforce some output style or (b) allow the Bibfish user to pass lots of options through to BibtexParser.

I'm curious though: what do your weird bibtex entries look like? Perhaps they can still be accommodated within the simple regex approach.

**Comment by rbeyer** [comment]
Firstly, I appear to have citekeys with a period (".") in them, which is a regex special character, which can cause some oddness in the match in *extract_bibtex_entries()* but that's easily fixed with running `re.escape()` on the cite key before combining it with the other r-strings and passing the result to *re.search()*.

The more important difference is that not all of my .bib entries end with r"\n\}\n".  Sometimes the ending curly brace is on the same line as the last tag in the entry.  There's also nothing preventing a right-curly brace being on a line on its own within a BibTex entry as part of the terminating bracket of a tag as part of the entry, but not the terminating bracket of the entry.

I appreciate that you may not want to take on dependencies, and that's fine.  Designing software is always about picking a path between requirements.  For me, I don't care how the tags in a BibTex entry are arranged in the *bibfish* output, what's valuable to me is the ability to pick out the entries without having to do it by hand.  If preserving the plain-text arrangement of the tags (and possibly comments) inside a bibtex entry is important to your vision of *bibfish* and you don't want to take on the BibtexParser dependency, then that's that, and I absolutely respect it.

I'll note that the default parsing strategy from BibtexParser is conservative by design, a parser instance can be instantiated and modifed it to be more ... omnivorous ... so that it would happily consume your `@presentation`, `@magazine`, or any other type that it considers non-standard, and for the *bibfish* use case, I think we'd tune BibtexParser to be as accepting as possible (and not deal with exposing complexity to *bibfish* users).

I've offered the PR because I need changes for my use case, but I will not be offended at all if you don't want to take on that dependency, which is why I asked, and will be happy to use my own modified version of *bibfish*.

**Comment by jwcarr** [comment]
> that's easily fixed with running re.escape() on the cite key

Ah, yes, this we should definitely fix.

> The more important difference is that not all of my .bib entries end with r"\n}\n".

Yep, I knew this was a horrible hack when I wrote it. And I'm sure this has presented a problem for many potential users who just gave up.

You're right that, in order to support a wider range of files, Bibfish really needs to do a proper, robust parse of the bibtex. And I can also see that parsing the bibtex would probably have some other side-benefits too – it would simplify some of the code and permit more expansion options in the future. And, if we can make it omnivorous, as you say, then I'd be happy with that.

So, on balance, yes, let's do this.

**Comment by rbeyer** [comment]
Okay, cool.  I will craft a rather meaty PR based on these discussions that will add the BibtexParser dependency as well as the multi-bib capability we're talking about in #4.  Might take me a week or so.

**Comment by jwcarr** [comment]
Thanks for all your work on this! I have done a little bit of tidying up of PR #6 and pushed a new release (v.0.2.0). Let me know in case there are any issues. The only substantial thing I changed was to remove the messages about the number of citekeys found etc., since I prefer silent functioning by default (but happy to add a verbose option if you like this).

**Comment by rbeyer** [comment]
That's fine, I should have cleaned up all of those debugging print statements.
